### PR TITLE
update build step 

### PR DESCRIPTION
**Pull request by lvgithub**
add: git submodule update --init

### CODE REVIEW

**Comment by lvgithub** [comment]
@yuqingc , I succeeded in solving the problem(#60),when is run 'git submodule update --init' before run '.build.py', if you had error ,please make sure you have a good internet connection

**Comment by lvgithub** [comment]
@yuqingc  I succeeded in solving the problem(#60),when is run 'git submodule update --init' before run '.build.py', if you had error ,please make sure you have a good internet connection

**Comment by FrankFang** [comment]
@yuqingc  Use a vpn, it helps.

**Comment by ry** [comment]
This shouldn't be necessary.

**Comment by seishun** [comment]
@ry Could you clarify why this isn't necessary?

**Comment by ry** [comment]
@seishun I believe “go get” checks out submodules..?

**Comment by seishun** [comment]
@ry It doesn't for me, probably because I tried with an ancient version of go (go1.3.3). It's understandable if building deno requires a newer go version, but the README should mention it. Do you know since when `go get` started checking out submodules?

**Comment by seishun** [comment]
I think this is the relevant commit: https://github.com/golang/go/commit/a444da033c0bc1fa5fb1973bd6d0c131ec3c1ccd

So go1.6 seems to be the minimum supported version.

**Comment by lvgithub** [comment]
@ry @seishun  my go version is go1.10.2, but  “go get” did not checks out submodules。

**Comment by ry** [comment]
Oh - sorry - I was mistaken. Added something to readme in a315d1ef97f36603cb343280c530d1cb5a0130c8

**Pull request closed without merging**
