### PR TITLE
Delete go implementation

### PR DESCRIPTION
**Pull request by ry**
The old implementation will stay around at: https://github.com/ry/deno/tree/golang

I want to delete these files to reduce confusion

After this we will rename deno2 to src

#270 should be landed first

### CODE REVIEW

**Comment by tmc** [comment]
Was looking forward to having a solid embeddable runtime for ts in go programs. Alas.

**Comment by ry** [comment]
@tmc the double GC problem is too worrying to invest more into it.

**Comment by piscisaureus** [comment]
LGTM

**Comment by piscisaureus** [comment]
But lets rebase it first and see if travis still passes.

**Pull request merged**
