### PR TITLE
Use template literals instead of traditional string concatenation

### PR DESCRIPTION
**Pull request by kizerkizer**
I rewrote a number of lines where traditional string concatenation was used in favor of the contemporary template literal syntax.

### CODE REVIEW

**Comment by kizerkizer** [comment]
All of these 4 commits are mine. Somehow I managed to do so under 4 different usernames.

**Comment by chainhelen** [comment]
@kizerkizer You can `git rebase -i` and `git push -f ` to merge three commits into only one.

**Comment by kevinkassimo** [comment]
Agreed, updating my PR to also reflect this

**Comment by kizerkizer** [comment]
I've managed to squash, I believe. Got lost in git land for a while...

**Comment by kizerkizer** [comment]
@qti3e Ready to merge?

**Comment by sijad** [comment]
need to be rebased again I guess

**Comment by kizerkizer** [comment]
@ry merge?

**Comment by ry** [comment]
@kizerkizer Thanks for the clean up! (Sorry for the delay - I'm backed up in reviewing patches...)

**Comment by chainhelen** [comment]
En, sorry for this trouble. one care about what I comment this pr.   
I'm not very sure whether this issue is necessary, so I say again. 


image    


image  

These are  not the same style in this pr. There is an unnecessary space in the first picture.

**Comment by gillchristian** [comment]
@chainhelen prettier should fix that :wink:

**Pull request merged**
