### PR TITLE
Implement statSync

### PR DESCRIPTION
**Pull request by gillchristian**
Implemented statSync (from [TODO](https://github.com/ry/deno/blob/master/TODO.txt#L3-L4)).

I'm not sure about what stats are required, used the ones from [`os.FileInfo`](https://golang.org/pkg/os/#FileInfo). Are those ok?

**TODO**: fix conflicting command numbers if other PRs get merged first (i.e. #209, #229, #5).

### CODE REVIEW

**Comment by monkingxue** [comment]
[#98](https://github.com/ry/deno/pull/98) Duplicate?

**Comment by gillchristian** [comment]
@monkingxue you are right :man_facepalming:

**Comment by piscisaureus** [comment]
This approach doesn't work when the source file contains an import statement.

**Comment by gillchristian** [comment]
> This approach doesn't work when the source file contains an import statement.

@piscisaureus was that meant for #247 ? If so, yes you are right. It does not work in many cases, I'm working on a proper solution, just experimenting with different approaches.

**Comment by piscisaureus** [comment]
@gillchristian: oops, my bad

**Comment by ry** [comment]
@gillchristian thanks - but we're in the middle of a rewrite and need to come back to this later. Sorry about this. I'm closing this PR - I will revisit statSync hopefully next week.

**Pull request closed without merging**
